"""v1.0

Revision ID: 281e32ecd391
Revises: 599c9cca170b
Create Date: 2019-12-18 23:42:59.239878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281e32ecd391'
down_revision = '599c9cca170b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nercontentsegs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nertag', sa.String(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['wordsegs.id'], name=op.f('fk_nercontentsegs_word_id_wordsegs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nercontentsegs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nercontentsegs')
    # ### end Alembic commands ###
