"""v1.0

Revision ID: 599c9cca170b
Revises: a04c5a468b8a
Create Date: 2019-12-18 22:45:22.961753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599c9cca170b'
down_revision = 'a04c5a468b8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postcontentsegs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('word_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_postcontentsegs_chapter_id_sentencesegs', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_postcontentsegs_word_id_wordsegs'), 'wordsegs', ['word_id'], ['id'])
        batch_op.drop_column('chapter_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postcontentsegs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapter_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_postcontentsegs_word_id_wordsegs'), type_='foreignkey')
        batch_op.create_foreign_key('fk_postcontentsegs_chapter_id_sentencesegs', 'sentencesegs', ['chapter_id'], ['id'])
        batch_op.drop_column('word_id')

    # ### end Alembic commands ###
