"""v1.0

Revision ID: 6b2af29ca51e
Revises: 
Create Date: 2019-12-11 23:45:59.452723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2af29ca51e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.String(length=64), nullable=True),
    sa.Column('book_url', sa.String(), nullable=True),
    sa.Column('book_img', sa.String(), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('last_update', sa.String(length=64), nullable=True),
    sa.Column('profile', sa.Text(), nullable=True),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.create_index(op.f('ix_novels_book_name'), 'novels', ['book_name'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter', sa.String(length=64), nullable=True),
    sa.Column('chapter_url', sa.String(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_chapter_url'), 'chapters', ['chapter_url'], unique=False)
    op.create_table('contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postcontentsegs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wordseg', sa.String(), nullable=True),
    sa.Column('postag', sa.String(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wordsegs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wordseg', sa.String(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wordsegs')
    op.drop_table('postcontentsegs')
    op.drop_table('contents')
    op.drop_index(op.f('ix_chapters_chapter_url'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_novels_book_name'), table_name='novels')
    op.drop_table('novels')
    # ### end Alembic commands ###
