"""v1.0

Revision ID: 8548b53d6da3
Revises: 6b2af29ca51e
Create Date: 2019-12-14 17:53:13.112837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8548b53d6da3'
down_revision = '6b2af29ca51e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentiContent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentence', sa.Text(), nullable=True),
    sa.Column('senti', sa.String(), nullable=True),
    sa.Column('degree', sa.Float(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentiContent')
    # ### end Alembic commands ###
